export const links = {
  docs: {
    home: 'https://docs.hypurr.fi/introduction/hypurrfi',
    eMode: '',
    isolationMode: '',
    siloedMode: '',
    isolationModeBorrowingPower: '',
    supplyBorrowCaps: '',
    dsr: '',
    ssr: '',
    upgradeDai: '',
    upgradeSdai: '',
    downgradeUsds: '',
    newSavings: '',
    healthFactor: '',
    supplying: '',
    borrowing: '',
    sparkAirdrop: '',
    farmingRewards: '',
  },
  aaveTechnicalPaper: '',
  termsOfUse: '',
  privacyPolicy: '',
  social: {
    x: 'https://x.com/hypurrfi',
    telegram: 'https://t.me/+YvsBvSxlQrVhNDkx',
    github: 'https://github.com/lastdotnet',
  },
  audits: '/',
  privacy: '/',
} as const
